config/routes.rb
Rails.application.routes.draw do
  resources :match_picks

  resources :matches

  root :to=>"home#index"
  get "sign_in" => "authentication#sign_in"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "sign_in" => "authentication#login"
  put "sign_in" => "authentication#login"
  post "new_user" => "authentication#register"
  put "new_user" => "authentication#register"
  get "admin_users" => "admin#users"
  delete "user/:id" => "admin#delete_user", :as => "user"
  get "admin_users" => "authentication#admin_users"
  get '/home', to: 'userhome#home'
  get '/instructions', to: 'home#instructions'
  get '/blocks', to: 'matches#blocks'  
  post "match/create-match-pick" => "matches#create_match_pick", :as => :create_match_pick
  get "update_score" => "matches#update_match_score", :as => :update_score
  post "update_score" => "matches#update_match_score", :as => :update_match_score
  get "account_settings" => "authentication#account_settings"
  put "account_settings" => "authentication#set_account_info"
  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"
  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"
  get "leagues_overall" => "leagues#overall"
    

end

app/controllers/authentication_controller.rb
# Class written by Alan Dunne after following tutorials by Marc Clifton [Available @ http://www.codeproject.com/Articles/575551/User-Authentication-in-Ruby-on-Rails#AdministratingUsers78]
class AuthenticationController < ApplicationController
 
  @@registration_close = '28th May 2014 22:10 +01:00'
  
  def sign_in
    @user = User.new
  end

  def login
    username_or_email = params[:user][:username]
    password = params[:user][:password]

    if username_or_email.rindex('@')
      email=username_or_email
      user = User.authenticate_by_email(email, password)
    else
      username=username_or_email
      user = User.authenticate_by_username(username, password)
    end

    if user
      update_authentication_token(user, params[:user][:remember_me])
      user.last_signed_in_on=DateTime.now
      user.save
      session[:user_id] = user.id
      flash[:notice] = 'Welcome' 
      redirect_to '/home'
    else
      flash.now[:error] = 'Unknown user. Please check your username and password.'
      
      # Assign user to instance variable for the `sign_in` view!
      @user = User.new(params[:user]) 
      
      render :action => "sign_in"
    end
  end
  
  def signed_out
    # clear the authentication toke when the user manually signs out
    user = User.find_by_id(session[:user_id])
    
    if user
      update_authentication_token(user, nil)
      user.save
      session[:user_id] = nil
      flash[:notice] = "You have been signed out."
    else
      redirect_to :sign_in
    end
  end   
    
  
  def new_user
    if (DateTime.now > @@registration_close.to_datetime)
      @user = User.new
    else
      flash[:notice] = 'Sorry but registration closed at 17:00 on 12th June 2014'
      redirect_to :root      
    end
    
  end
  
  def register
    if (DateTime.now > @@registration_close.to_datetime)
      @user = User.new(params[:user])

      if @user.valid?
        update_authentication_token(@user, nil)
        @user.signed_up_on = DateTime.now
        @user.last_signed_in_on = @user.signed_up_on
        @user.curr_block = 0
        @user.points = 0
        @user.save
        UserMailer.welcome_email(@user).deliver
        session[:user_id] = @user.id
        flash[:notice] = 'Welcome.'
        redirect_to :root
      else
        render :action => "new_user"
      end
    else
      flash[:notice] = 'Sorry but registration closed at 17:00 on 12th June 2014'
      redirect_to :root
    end
  end  
  
  def account_settings
    @user = current_user
  end
  
  def set_account_info
    old_user = current_user

    # verify the current password by creating a new user record.
    @user = User.authenticate_by_username(old_user.username, params[:user][:password])

    # verify
    if @user.nil?
      @user = current_user
      @user.errors[:password] = "Password is incorrect"
      render :action => "account_settings"
    else
      # update the user with any new username and email
      @user.update(params[:user])
      # Set the old email and username, which is validated only if it has changed.
      @user.previous_email = old_user.email
      @user.previous_username = old_user.username

      if @user.valid?
        # If there is a new_password value, then we need to update the password.
        @user.password = @user.new_password unless @user.new_password.nil? || @user.new_password.empty?
        @user.save
        flash[:notice] = 'Account settings have been changed'
        redirect_to :root
      else
        render :action => "account_settings"
      end
    end
  end
  
  # HTTP get
  def forgot_password
    @user = User.new
  end

  # HTTP put
  def send_password_reset_instructions
    username_or_email = params[:user][:username]

    if username_or_email.rindex('@')
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user
      user.password_reset_token = SecureRandom.urlsafe_base64
      user.password_expires_after = 24.hours.from_now
      user.save
      UserMailer.reset_password_email(user).deliver
      flash[:notice] = 'Password instructions have been mailed to you. Please check your inbox.'
      redirect_to :sign_in
    else
      @user = User.new
      # put the previous value back.
      @user.username = params[:user][:username]
      @user.errors[:username] = 'is not a registered user.'
      render :action => "forgot_password"
    end
  end  
  
  # The user has landed on the password reset page, they need to enter a new password.
  # HTTP get
  def password_reset
    token = params.first[0]
    @user = User.find_by_password_reset_token(token)

    if @user.nil?
      flash[:error] = 'You have not requested a password reset.'
      redirect_to :root
      return
    end

    if @user.password_expires_after < DateTime.now
      clear_password_reset(@user)
      @user.save
      flash[:error] = 'Password reset has expired. Please request a new password reset.'
      redirect_to :forgot_password
    end
  end  
  
  # The user has entered a new password. Need to verify and save.
  # HTTP put
  def new_password
    username = params[:user][:username]
    @user = User.find_by_username(username)

    if verify_new_password(params[:user])
      @user.update(params[:user])
      @user.password = @user.new_password

      if @user.valid?
        clear_password_reset(@user)
        @user.save
        flash[:notice] = 'Your password has been reset. Please sign in with your new password.'
        redirect_to :sign_in
      else
        render :action => "password_reset"
      end
    else
      @user.errors[:new_password] = 'Cannot be blank and must match the password verification.'
      render :action => "password_reset"
    end
  end  
  
  
  
  
  # ========= Private Functions ==========
  
  private

  def clear_password_reset(user)
    user.password_expires_after = nil
    user.password_reset_token = nil
  end

  def verify_new_password(passwords)
    result = true

    if passwords[:new_password].blank? || (passwords[:new_password] != passwords[:new_password_confirmation])
      result = false
    end

    result
  end  
  
  def update_authentication_token(user, remember_me)
    if remember_me == 1
      # create an authentication token if the user has clicked on remember me
      auth_token = SecureRandom.urlsafe_base64
      user.authentication_token = auth_token
      cookies.permanent[:auth_token] = auth_token
    else # nil or 0
      # if not, clear the token, as the user doesn't want to be remembered.
      user.authentication_token = nil
      cookies.permanent[:auth_token] = nil
    end
  end  
  
end

app/views/authentication/account_settings.html.erb
<%= form_for @user, :as => :user, :url => account_settings_path, :method => :put do |f| %>
 
<div class="row">
  <form class="form-horizontal">
    <fieldset>

      <!-- Form Name -->
      <legend>Account Settings</legend>

      <!-- existing password input -->
      <div class="control-group">
        <div class="controls">
          <p><%= f.label 'current password:' %></p>
          <p><%= f.password_field :password, :required => true %></p>   
          <p class="help-block"><%= show_field_error(@user, :password) %></p><br/> 
        </div>
      </div>

      <!-- new username input-->
      <div class="control-group">
        <div class="controls">
          <p><%= f.label 'username: (leave unchanged if you are not changing your username)' %></p>
          <p><%= f.text_field :username %></p>
          <p class="help-block"><%= show_field_error(@user, :username) %></p><br/>
        </div>
      </div>

      <!-- new email input-->
      <div class="control-group">
        <div class="controls">
          <p><%= f.label 'email: (leave unchanged if you are not changing your email address)' %></p>
          <p><%= f.text_field :email %></p>
          <p class="help-block"><%= show_field_error(@user, :email) %></p><br/>
        </div>
      </div>

      <!-- new password input-->
      <div class="control-group">
        <div class="controls">
          <p><%= f.label 'new password: (leave blank if you are not changing your password)' %></p>
          <p><%= f.password_field :new_password %></p>
          <p class="help-block"><%= show_field_error(@user, :new_password) %></p><br/>
        </div>
      </div> 

      <!-- new password confirmation -->
      <div class="control-group">
        <div class="controls">
          <p><%= f.label 'password confirmation:' %></p>
          <p><%= f.password_field :new_password_confirmation, placeholder: 'password confirmation:' %></p>
          <p class="help-block"><%= show_field_error(@user, :new_password_confirmation) %></p><br/>
        </div>
      </div>

      <!-- Submit button -->
      <div class="control-group">
        <div class="controls">
          <%= f.submit 'Update' ,:class => "btn btn-success" %>
        </div>
      </div>

    </fieldset>

  </form>
</div>  

<% end %>

app/views/authentication/forgot_password.html.erb
<%= form_for @user, :as => :user, :url => forgot_password_path, :method => :put do |f| %>
  
  <form class="form-horizontal">
    <fieldset>
      <!-- Form Name -->
      <legend>Forgot Password</legend>
      
      <!-- Enter username or password -->
      <div class="control-group">
        <div class="controls">
          <p><%= f.label 'username or email:' %></p><br/>
          <p><%= f.text_field :username %></p>   
          <p><%= show_field_error(@user, :username) %></p>
        </div>
      </div>

      <!-- Button (Double) -->
      <div class="control-group">
        <div class="controls">
          <p><%= f.submit 'Send Password Reset Instructions' ,:class => "btn btn-success" %></p>
         </div>
      </div>
       
    </fieldset> 
  </form> 
<% end %>      

app/views/authentication/new_user.html.erb
<!--# Written by Alan Dunne after following tutorials by Marc Clifton [Available @ http://www.codeproject.com/Articles/575551/User-Authentication-in-Ruby-on-Rails#AdministratingUsers78]-->
<%= form_for @user, :as => :user, :url => new_user_path, :method => :put do |f| %>
 
<form class="form-horizontal">
<fieldset>

  <!-- Form Name -->
  <legend>Sign Up</legend>
  
  <!-- username input-->
  <div class="control-group">
    <div class="controls">
      <p><%= f.text_field :username, placeholder: 'username', :required => true %></p>    
      <p class="help-block"><%= show_field_error(@user, :username) %></p>
    </div>
  </div>

  <!-- email input-->
  <div class="control-group">
    <div class="controls">
      <p><%= f.text_field :email, placeholder: 'email', :required => true %></p> 
      <p class="help-block"><%= show_field_error(@user, :email) %></p>
    </div>
  </div>

  <!-- Password input-->
  <div class="control-group">
    <div class="controls">
      <p><%= f.password_field :password, placeholder: 'password', :required => true %></p> 
      <p class="help-block"><%= show_field_error(@user, :password) %></p>
    </div>
  </div>

  <!-- Password input-->
  <div class="control-group">
    <div class="controls">
      <p><%= f.password_field :password_confirmation, placeholder: 'password confirmation',:required => true %></p> 
      <p class="help-block"><%= show_field_error(@user, :password_confirmation) %></p>
    </div>
  </div>

  <!-- Button (Double) -->
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Sign Up' ,:class => "btn btn-success" %>
      <%= f.submit 'Clear Form', :class => "btn btn-success",:type => 'reset' %>    
    </div>
  </div>
  
    <!-- Get token if want to be remembered -->  
    <div class="control-group">
      <div class="controls">   
        <%= f.check_box :remember_me %><%= f.label 'remember me' %>      
      </div>
    </div>    

</fieldset>
</form>   

<% end %>

app/views/authentication/password_reset.html.erb
<%= form_for @user, :as => :user, :url => password_reset_path, :method => :put do |f| %>
  
  <form class="form-horizontal">
    <fieldset>
      <!-- Form Name -->
      <legend>Account Settings</legend>

      <p>
        <%= @user.username  %> has requested a password reset.  Please enter your new password:
      </p>
      
      <!-- Enter new password -->
      <div class="control-group">
        <div class="controls">
          <p><%= f.label 'new password:' %></p>
          <p><%= f.password_field :new_password %></p>   
          <p><%= show_field_error(@user, :new_password) %></p>
        </div>
      </div>
      
      <div class="control-group">
        <div class="controls">
          <p><%= f.hidden_field :username %></p>
          <p><%= f.label 'password confirmation:' %></p>
          <p><%= f.password_field :new_password_confirmation %></p>   
          <p><%= show_field_error(@user, :new_password_confirmation) %></p>
        </div>
      </div>      
      
      <!-- Button (Double) -->
      <div class="control-group">
        <div class="controls">
          <p><%= f.submit 'Update' ,:class => "btn btn-success" %></p>
         </div>
      </div>
       
    </fieldset> 
  </form> 
<% end %>
  

app/views/authentication/sign_in.html.erb
<!--# Written by Alan Dunne after following tutorials by Marc Clifton [Available @ http://www.codeproject.com/Articles/575551/User-Authentication-in-Ruby-on-Rails#AdministratingUsers78]-->
<%= form_for @user, :as => :user, :url => sign_in_path(@user) do |f| %>

<form class="form-horizontal">
  <fieldset>

      <!-- Form Name -->
      <legend>Sign In</legend>

      <!-- username or email input-->
      <div class="control-group">
        <div class="controls">
          <%= f.text_field :username,placeholder: 'username or email', :required => true %>   
          <%= show_field_error(@user, :username) %>
        </div>
      </div>


    <!-- Password input-->
    <div class="control-group">
      <div class="controls">
        <%= f.password_field :password, placeholder: 'password',:required => true %>
        <p class="help-block"><%= show_field_error(@user, :password) %></p>
      </div>
    </div>

    <!-- Submit / Rest buttons -->
    <div class="control-group">
      <div class="controls">
        <%= f.submit 'Sign In' ,:class => "btn btn-success" %>
        <%= f.submit 'Clear Form', :class => "btn btn-success",:type => 'reset' %>    
      </div>
    </div>
    
    <!-- Get token if want to be remembered -->  
    <div class="control-group">
      <div class="controls">   
        <%= f.check_box :remember_me %><%= f.label 'remember me' %>      
      </div>
    </div>  
    

<% end %>    
    
    <!-- Forgot Password -->
    <div class="control-group">
      <div class="controls">
        <%= link_to 'Forgot password?', :forgot_password, :class => "btn btn-success" %>
     </div>
    </div>  



  </fieldset>
</form>  
   

app/views/authentication/signed_out.html.erb
<div></div>