config/routes.rb
Rails.application.routes.draw do
  resources :match_picks

  resources :matches

  root :to=>"home#index"
  get "sign_in" => "authentication#sign_in"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "sign_in" => "authentication#login"
  put "sign_in" => "authentication#login"
  post "new_user" => "authentication#register"
  put "new_user" => "authentication#register"
  get "admin_users" => "admin#users"
  delete "user/:id" => "admin#delete_user", :as => "user"
  get "admin_users" => "authentication#admin_users"
  get '/home', to: 'userhome#home'
  get '/instructions', to: 'home#instructions'
  get '/blocks', to: 'matches#blocks'  
  post "match/create-match-pick" => "matches#create_match_pick", :as => :create_match_pick
  get "update_score" => "matches#update_match_score", :as => :update_score
  post "update_score" => "matches#update_match_score", :as => :update_match_score
  get "account_settings" => "authentication#account_settings"
  put "account_settings" => "authentication#set_account_info"
  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"
  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"
  get "leagues_overall" => "leagues#overall"
    

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :block, :round, :date, :day, :time, :venue, :team1, :team2, :played, :result, :resultString
  has_many :match_picks
  has_many :current_blocks
  after_create :set_expiry_timer
  
    # register the timer
  def set_expiry_timer
    self.delay_for(5.minutes).assign_picks
  end  

  
  def assign_picks
    @current_blocks = CurrentBlock.where(:id => 1)
    @users = User.where(:curr_block != @current_blocks[0].block)
    @matches = Match.where(:block => @current_blocks[0].block)    
         
    @users.each do |user|
      @matches.each do |match|
        MatchPick.create!(:userID => user.id, :matchID => match.id, :blockID => @current_blocks[0].block, :userPick => (0..2).to_a.sample)
      end
    end
      # Increase the current block for application
       CurrentBlock.where(:id => 1).each do |cb|
        cb.update_attribute(:block, cb.block + 1)
     end      
  end  
  
end

app/models/user.rb
# Class written by Alan Dunne after following tutorials by Marc Clifton [Available @ http://www.codeproject.com/Articles/575551/User-Authentication-in-Ruby-on-Rails#AdministratingUsers78]
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation, :admin, :new_password, :new_password_confirmation, :remember_me, :curr_block, :points
  attr_accessor :password, :new_password, :previous_email, :previous_username, :remember_me
  before_save :encrypt_password
  has_many :match_picks
  has_many :matches, through: :match_picks

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :if => Proc.new {|user| 
    user.previous_email.nil? || user.email != user.previous_email}
  validates_presence_of :username, :if => Proc.new {|user| 
    user.previous_username.nil? || user.username != user.previous_username}
  validates_uniqueness_of :email, :if => Proc.new {|user| 
    user.previous_email.nil? || user.email != user.previous_email}
  validates_uniqueness_of :username, :if => Proc.new {|user| 
    user.previous_username.nil? || user.username != user.previous_username}
  validates_confirmation_of :new_password, :if => Proc.new {|user| !user.new_password.nil? && !user.new_password.empty? }

  def self.authenticate_by_email(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def self.authenticate_by_username(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
    
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end    
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  # GET /matches
  # GET /matches.json

  def index
    if((params[:block].to_i == 0)&&(current_user.admin == true))    
      @matches = Match.all.order(:id)
      puts params #Debug
    elsif (params[:block].to_i.between?(current_user.curr_block,10))  
      @matches = Match.where(:block => params[:block].to_i).order(:id)     
    else    
      flash[:error] = 'Not a valid block'
      redirect_to :blocks
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update      
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
    
    MatchPick.where(:matchID => params[:id]).update_all(result: match_params[:result], closed: match_params[:played], points: 0)
    MatchPick.where(:matchID => params[:id], :userPick => match_params[:result]).update_all(points: 3)
    update_user_points
    assign_picks
    
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
  
  def update_user_points
    MatchPick.where(:matchID => params[:id], :userPick => match_params[:result]).each do |mp|
      mp.user.update_attribute(:points, mp.user.points + 3)
      puts params
    end
  end
  
    
  def create_match_pick
     if params[:match_ids].nil?
       redirect_to matches_url, :flash => { :error => 'Your notice or whatever' } 
     else
       @user = current_user 
       puts "The user's email is " + @user.email # Debug
       @matches = Match.find(params[:match_ids])
       @userpick = params[:user_picks] unless params[:user_picks].nil?
       @user.curr_block = @matches[0].block.to_i
       @user.save
       puts "The user's curr_block = " + @user.curr_block.to_s # Debug
       @matches.each_with_index do |match, index|
         MatchPick.create!(:userID => session[:user_id], :matchID => match.id, :blockID => match.block, :userPick => @userpick[index] ) 
         if @matches.size == index + 1
           redirect_to blocks_path
         end
        end       
     end
  end  
  
  def assign_picks
    @current_blocks = CurrentBlock.where(:id => 1)
    @users = User.where(:curr_block != @current_blocks[0].block)
    @matches = Match.where(:block => @current_blocks[0].block)    
         
    @users.each do |user|
      @matches.each do |match|
        MatchPick.create!(:userID => user.id, :matchID => match.id, :blockID => @current_blocks[0].block, :userPick => (0..2).to_a.sample)
      end
    end
      # Increase the current block for application
       CurrentBlock.where(:id => 1).each do |cb|
        cb.update_attribute(:block, cb.block + 1)
     end      
  end  
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:block, :round, :date, :day, :time, :venue, :team1, :team2, :result, :resultString, :played)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<div class= " col-md-1 text-center">
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :block %><br>
    <%= f.number_field :block %>
  </div>
  <div class="field">
    <%= f.label :round %><br>
    <%= f.text_field :round %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :team1 %><br>
    <%= f.text_field :team1 %>
  </div>
  <div class="field">
    <%= f.label :team2 %><br>
    <%= f.text_field :team2 %>
  </div>
  <div class="field">
    <%= f.label :result %>(0 for draw, 1 for Team1, 2 for Team2)<br>
    <%= f.number_field :result %>
  </div>
  <div class="field">
    <%= f.label :resultString %><br>
    <%= f.text_field :resultString %>
  </div>
  <div class="field">
    <%= f.label :played %><br>
    <%= f.check_box :played %>
  </div>
  <div class="actions">
    
    
    
    
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/matches/blocks.html.erb
  <h1>Match Blocks</h1>

<div class= "span10 center-table">
  <p id="notice"><%= notice %></p>
      <% today=DateTime.now %>
      <% block1Close = "12th June 2014 19:00 +01:00" %>
      <% block2Close = "15th June 2014 15:00 +01:00" %>
      <% block3Close = "18th June 2014 15:00 +01:00" %>
      <% block4Close = "21st June 2014 15:00 +01:00" %>
      <% block5Close = "24th June 2014 15:00 +01:00" %>
      <% block6Close = "28th June 2014 15:00 +01:00" %>
      <% block7Close = "30th June 2014 15:00 +01:00" %>
      <% block8Close = "4th July 2014 15:00 +01:00" %>
      <% block9Close = "8th July 2014 19:00 +01:00" %>
      <% block10Close = "12th July 2014 19:00 +01:00" %>

  <table class="table table-bordered table-condensed table-striped" style="background-color: #d9edf7;">
    <thead>
      <tr>
        <th class="col-sn-1">Stage</th>
        <th class="col-sn-1">Button</th>
        <th class="col-sn-1">Status</th>
        <th class="col-sn-1">Closing</th>
      </tr>
    </thead>  
  
  <tbody>  
     <tr>
       <td>Group stages</td>
        <% if ((today<=block1Close.to_datetime)&&(current_user.curr_block < 1)) %>
          <td><%= link_to "Block 1", matches_path(:block => 1), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 1", match_picks_path(:block => 1), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block1Close.to_datetime)&&(current_user.curr_block < 1)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block1Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr>
    
     <tr>
       <td>Group stages</td>
        <% if ((today<=block2Close.to_datetime)&&(current_user.curr_block < 2)) %>
          <td><%= link_to "Block 2", matches_path(:block => 2), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 2", match_picks_path(:block => 2), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block2Close.to_datetime)&&(current_user.curr_block < 2)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block2Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr>  
    
     <tr>
       <td>Group stages</td>
        <% if ((today<=block3Close.to_datetime)&&(current_user.curr_block < 3)) %>
          <td><%= link_to "Block 3", matches_path(:block => 3), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 3", match_picks_path(:block => 3), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block3Close.to_datetime)&&(current_user.curr_block < 3)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block3Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr>       

     <tr>
       <td>Group stages</td>
        <% if ((today<=block4Close.to_datetime)&&(current_user.curr_block < 4)) %>
          <td><%= link_to "Block 4", matches_path(:block => 4), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 4", match_picks_path(:block => 4), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block4Close.to_datetime)&&(current_user.curr_block < 4)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block4Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr>     
    
     <tr>
       <td>Group stages</td>
        <% if ((today<=block5Close.to_datetime)&&(current_user.curr_block < 5)) %>
          <td><%= link_to "Block 5", matches_path(:block => 5), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 5", match_picks_path(:block => 5), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block5Close.to_datetime)&&(current_user.curr_block < 5)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block5Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr>  

     <tr>
       <td>Second Round</td>
        <% if ((today<=block6Close.to_datetime)&&(current_user.curr_block < 6)) %>
          <td><%= link_to "Block 6", matches_path(:block => 6), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 6", match_picks_path(:block => 6), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block6Close.to_datetime)&&(current_user.curr_block < 6)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block6Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr>  
    
     <tr>
       <td>Second Round</td>
        <% if ((today<=block7Close.to_datetime)&&(current_user.curr_block < 7)) %>
          <td><%= link_to "Block 7", matches_path(:block => 7), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 7", match_picks_path(:block => 7), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block7Close.to_datetime)&&(current_user.curr_block < 7)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block7Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr>  

     <tr>
       <td>Quarter Finals</td>
        <% if ((today<=block8Close.to_datetime)&&(current_user.curr_block < 8)) %>
          <td><%= link_to "Block 8", matches_path(:block => 8), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 8", match_picks_path(:block => 8), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block8Close.to_datetime)&&(current_user.curr_block < 8)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block8Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr> 
    
     <tr>
       <td>Semi Finals</td>
        <% if ((today<=block9Close.to_datetime)&&(current_user.curr_block < 9)) %>
          <td><%= link_to "Block 9", matches_path(:block => 9), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 9", match_picks_path(:block => 9), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block9Close.to_datetime)&&(current_user.curr_block < 9)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block9Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr> 
    
     <tr>
       <td>3rd/4th Playoff and Final</td>
        <% if ((today<=block10Close.to_datetime)&&(current_user.curr_block < 10)) %>
          <td><%= link_to "Block 10", matches_path(:block => 10), :class => "btn", :method => :get %></td>
        <% else %>
          <td><%= link_to "Block 10", match_picks_path(:block => 10), :class => "btn", :method => :get %></td>
        <% end %>    

        <% if ((today<=block10Close.to_datetime)&&(current_user.curr_block < 10)) %>
           <td><span class="badge badge-success">Open</span></td> 
           <td><%= block10Close %></td>
        <% else %>  
           <td><span class="badge badge-important">Submitted</span></td>          
           <td>Closed</td>
        <% end %>
    </tr> 
    
  </tbody>
    
</div>
 

app/views/matches/edit.html.erb
<div class= " col-md-1 text-center">
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>
</div>

app/views/matches/index.html.erb
<div class= "span20 center-table">

  <% if (params[:block].to_i == 0) %> 
    <h1>Administer matches</h1>
  <% else %>
    <h1>Block <%= @matches[0].block %></h1>
  <% end %>  

  <table class="table table-bordered table-condensed table-striped" >
    <thead>
      <tr>
        <th style = 'display: none'></th>       
        <th class="col-sn-1">ID</th>
        <th class="col-sn-1">Block</th>
        <th class="col-sn-1">Round</th>
        <th class="span2">Date</th>
        <th class="col-sn-1">Day</th>
        <th class="col-sn-1">Time</th>
        <th class="col-sn-1">Venue</th>
        <th class="col-sn-1">Team1</th>
        <th class="col-sn-1">Team2</th>
        <% if (params[:block].to_i == 0) %> 
          <th class="col-sn-1">Result</th>
          <th class="col-sn-1">Result String</th>
          <th class="col-sn-1">Played</th>
        <% else %>      
          <th class="col-sn-1">User Pick</th>
        <% end %>
        <th style = 'display: none'></th> 
      </tr>
    </thead>

    <tbody>
      <%= form_tag create_match_pick_path, :method => :post do %>
        <% @matches.each do |match| %>
          <tr>
            <td style = 'display: none'></td>
            <td><%= match.id %></td>
            <td><%= match.block %></td>
            <td><%= match.round %></td>
            <td><%= match.date %></td>
            <td><%= match.day %></td>
            <td><%= match.time %></td>
            <td><%= match.venue %></td>
            <td><%= match.team1 %></td>
            <td><%= match.team2 %></td>

            <% if (params[:block].to_i == 0) %> 
            <td><%= match.result %></td>
            <td><%= match.resultString %></td>
            <td><%= match.played %></td>
            <td><%= link_to 'Update', edit_match_path(match) %></td>
            <% else %>
            <td><%= select_tag "user_picks[]", options_for_select([["Draw", "0"], [match.team1, "1"], [match.team2, "2"]]), disabled: false, 'data-id' => match.id, :class => 'match_option' %></td>            
            <td style = 'display:none'><%= check_box_tag "match_ids[]", match.id, false, :class => 'matchid', checked: true %></td>
            
            <% end %>       
          </tr>
        <% end %>
    </tbody>      
  </table>   
        <% if ((params[:block].to_i != 0)&&(current_user.curr_block==params[:block].to_i - 1)) %> 
          <%= button_tag :class => "btn-large btn-primary" do %> Submit Picks <% end %> 
        <% else %> 
          <p>You must complete your block picks in order. Please submit Block <%= (current_user.curr_block)+1 %> picks first<p>
        <% end %>
  
      <% end %>
</div>

<script type="text/javascript">
$('.matchid').on('click', function () {
    var dataid = $(this).val();
    if (this.checked) {
        $('select[data-id="'+ dataid +'"]').prop('disabled', false);
    } else {
        $('select[data-id="'+ dataid +'"]').prop('disabled', true);
    }
}); 
</script>

app/views/matches/new.html.erb
<div class= " col-md-1 text-center">
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>
</div>

app/views/matches/show.html.erb
<div class= " col-md-6 text-center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Match:</strong>
  <%= @match.id %>
</p>

<p>
  <strong>Block:</strong>
  <%= @match.block %>
</p>

<p>
  <strong>Round:</strong>
  <%= @match.round %>
</p>

<p>
  <strong>Date:</strong>
  <%= @match.date %>
</p>

<p>
  <strong>Day:</strong>
  <%= @match.day %>
</p>

<p>
  <strong>Time:</strong>
  <%= @match.time %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @match.venue %>
</p>

<p>
  <strong>Team1:</strong>
  <%= @match.team1 %>
</p>

<p>
  <strong>Team2:</strong>
  <%= @match.team2 %>
</p>

<p>
  <strong>Result:</strong>
  <%= @match.result %>
</p>

<p>
  <strong>Resultstring:</strong>
  <%= @match.resultString %>
</p>

<p>
  <strong>Played:</strong>
  <%= @match.played %>
</p>

</div>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>

app/views/matches/update_match_score.html.erb
<div class= " col-md-1 text-center">
  <h1>Update score</h1>

  <div class= " col-md-1 text-center">
    <%= form_tag update_match_score_path, :method => :post do |f| %>    
      <div class="field">
        <%= f.label :block %><br>
        <%= f.number_field :block %>
      </div>
      <div class="field">
        <%= f.label :round %><br>
        <%= f.text_field :round %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date %>
      </div>
      <div class="field">
        <%= f.label :day %><br>
        <%= f.text_field :day %>
      </div>
      <div class="field">
        <%= f.label :time %><br>
        <%= f.text_field :time %>
      </div>
      <div class="field">
        <%= f.label :venue %><br>
        <%= f.text_field :venue %>
      </div>
      <div class="field">
        <%= f.label :team1 %><br>
        <%= f.text_field :team1 %>
      </div>
      <div class="field">
        <%= f.label :team2 %><br>
        <%= f.text_field :team2 %>
      </div>
      <div class="field">
        <%= f.label :result %>(0 for draw, 1 for Team1, 2 for Team2)<br>
        <%= f.number_field :result %>
      </div>
      <div class="field">
        <%= f.label :resultString %><br>
        <%= f.text_field :resultString %>
      </div>
      <div class="field">
        <%= f.label :played %><br>
        <%= f.check_box :played %>
      </div>
      <div class="actions">
        <%= button_tag :class => "btn-large btn-primary" do %> Update scores <% end %> 
      </div>
    <% end %>
  </div>

  <%= link_to 'Show', @match %> |
  <%= link_to 'Back', matches_path %>
  
</div>