config/routes.rb
Rails.application.routes.draw do
  resources :match_picks

  resources :matches

  root :to=>"home#index"
  get "sign_in" => "authentication#sign_in"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "sign_in" => "authentication#login"
  put "sign_in" => "authentication#login"
  post "new_user" => "authentication#register"
  put "new_user" => "authentication#register"
  get "admin_users" => "admin#users"
  delete "user/:id" => "admin#delete_user", :as => "user"
  get "admin_users" => "authentication#admin_users"
  get '/home', to: 'userhome#home'
  get '/instructions', to: 'home#instructions'
  get '/blocks', to: 'matches#blocks'  
  post "match/create-match-pick" => "matches#create_match_pick", :as => :create_match_pick
  get "update_score" => "matches#update_match_score", :as => :update_score
  post "update_score" => "matches#update_match_score", :as => :update_match_score
  get "account_settings" => "authentication#account_settings"
  put "account_settings" => "authentication#set_account_info"
  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"
  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"
  get "leagues_overall" => "leagues#overall"
    

end

app/controllers/userhome_controller.rb
class UserhomeController < ApplicationController
  before_filter :authenticate_user
end

app/views/userhome/home.html.erb
<div class= " col-md-1 text-center">

<h1>World Cup 2014 Pick A Winner</h1>
  <% if current_user.admin==true %>
    <%= link_to "Administer Users", admin_users_path, :id => "open-contacts-dialog-btn", :class => "btn btn-large btn-primary", :method => :get %>
    <%= link_to "Administer Matches", matches_path(:block => 0), :id => "open-contacts-dialog-btn", :class => "btn btn-large btn-primary", :method => :get %>
  <% end %> 
  
  <%= link_to "Match Blocks", blocks_path, :id => "open-contacts-dialog-btn", :class => "btn btn-large btn-primary", :method => :get %>
  
  
  
  
  
  
  
</div>