config/routes.rb
Rails.application.routes.draw do
  resources :match_picks

  resources :matches

  root :to=>"home#index"
  get "sign_in" => "authentication#sign_in"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "sign_in" => "authentication#login"
  put "sign_in" => "authentication#login"
  post "new_user" => "authentication#register"
  put "new_user" => "authentication#register"
  get "admin_users" => "admin#users"
  delete "user/:id" => "admin#delete_user", :as => "user"
  get "admin_users" => "authentication#admin_users"
  get '/home', to: 'userhome#home'
  get '/instructions', to: 'home#instructions'
  get '/blocks', to: 'matches#blocks'  
  post "match/create-match-pick" => "matches#create_match_pick", :as => :create_match_pick
  get "update_score" => "matches#update_match_score", :as => :update_score
  post "update_score" => "matches#update_match_score", :as => :update_match_score
  get "account_settings" => "authentication#account_settings"
  put "account_settings" => "authentication#set_account_info"
  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"
  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"
  get "leagues_overall" => "leagues#overall"
    

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PAW</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<br />
<% end %>  
  
  
  <div class= " col-md-1 text-center">
  <% if current_user %>
    <div>
      <h4>Logged in as: <%= current_user.username %> <br/><br/><br/>
      </h4>
    </div>
  <div>
    
    
    <%= link_to "Home", home_path, :id => "open-contacts-dialog-btn", :class => "btn-large btn-primary", :method => :get %>  
  
    <%= link_to "Account Settings", account_settings_path, :id => "open-contacts-dialog-btn", :class => "btn-large btn-primary", :method => :get %>    
    
    <%= link_to "Sign Out", signed_out_path, :id => "open-contacts-dialog-btn", :class => "btn-large btn-primary", :method => :get %>

    
  <% else %>
    <%= link_to "Sign Up", new_user_path, :id => "btn1 btn-large btn-primary", :class => "btn1 btn-large btn-primary", :method => :get %>
    <%= link_to "Sign In", sign_in_path, :id => "open-contacts-dialog-btn", :class => "btn2 btn-large btn-primary", :method => :get %>
  <% end %>
   
  <% if (current_page?('/instructions')&&(current_user)) %>
 
  <% else %>
    <%= link_to "How To Play", instructions_path, :id => "open-contacts-dialog-btn", :class => "btn2 btn-large btn-primary", :method => :get %> 
  <% end %>
  </div>
  </div>
  
  
  
  

<div class= " col-md-1 text-center">  
  <%= yield %>
</div>
  
</body>
</html>